# Run with 
# docker-compose -f docker-compose.yml -f docker-compose.node.yml up

version: '3.1'
services:
  node:
    build: ./aergo
    volumes:
      - ./data/aergo:/aergo/data
    ports:
      - 7846
      - 7845
