version: '3'
services:
  nginx:
    build:
      context: ./
      args:
        AERGO_NODE: ${AERGO_NODE}
    ports:
      - "8080:80"
    depends_on:
      - backend
  backend:
    build: ./backend
    expose:
      - 3000
    volumes:
      - ./backend/src:/backend/src
    depends_on:
      - db
    environment:
      - AERGO_NODE
      - AERGOSCAN_REINDEX
  db:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9300:9300"
      - "9200:9200"
    expose:
      - 9200
    volumes:
      - esdata:/usr/share/elasticsearch/data
    command: ["elasticsearch", "-Elogger.level=WARN"]

volumes:
  esdata:
    driver: local
